### PR TITLE
Publish but do not install tests

### PR DESCRIPTION
**Pull request by polyzen**
Also remove unused import and touch up formatting.

Edit: Not sure if there's a way to make `test_suite` work with this, but tests do run with `python -m unittest discover tests`.

### CODE REVIEW

**Comment by jelmer** [comment]
This looks reasonable, but please keep changes minimal - i.e. please revert the indentation changes in setup.py and the move of tests/ to the root.

**Comment by polyzen** [comment]
On November 21, 2018 7:57:56 AM EST, "Jelmer Vernooĳ" <notifications@github.com> wrote:
>This looks reasonable, but please keep changes minimal - i.e. please
>revert the indentation changes in setup.py and the move of tests/ to
>the root.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jelmer/xandikos/pull/86#issuecomment-440653478

The indentation seemed erroneous as it didn't match the indent earlier in `setup.py`. Afaik, moving `tests/` out has to be done to keep it from being installed.

-- 
Best,
polyzen

**Comment by jelmer** [comment]
On Wed, Nov 21, 2018 at 05:00:33AM -0800, Daniel M. Capella wrote:
> On November 21, 2018 7:57:56 AM EST, "Jelmer Vernooĳ" <notifications@github.com> wrote:
> >This looks reasonable, but please keep changes minimal - i.e. please
> >revert the indentation changes in setup.py and the move of tests/ to
> >the root.
> The indentation seemed erroneous as it didn't match the indent earlier in `setup.py`. Afaik, moving `tests/` out has to be done to keep it from being installed.

I might hold off on this in that case. Happy to consider this if
there's a reason to stop installing the tests (e.g. if they get too
big). Please feel free to reopen.

The existing indentation is PEP8 compliant, whereas with your change
the first line has different indentation than the latter ones.

See https://www.python.org/dev/peps/pep-0008/#id17
("Aligned with opening delimiter.")

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by polyzen** [comment]
For future reference, it appears a simple change to `package=` would accomplish this.

**Pull request closed without merging**
