### PR TITLE
Use correct mimetypes

### LINKED ISSUE #30: mimetypes.guess_type guesses the wrong vcard mimetype
>>> mimetypes.guess_type('foo.vcf')
    ('text/x-vcard', None)

This breaks multiget for `address-data` for instance. I would recommend having a hardcoded translation table for the two mimetypes you actually need to support, instead of using `mimetypes`.

### PR DESCRIPTION
**Pull request by untitaker**
Fix #30

### CODE REVIEW

**Comment by jelmer** [comment]
The guessed mimetypes also matter for any files that are stored that are not vcard or icalendar files.

Could we rather just allow FileHandler to register multiple mimetypes (text/x-vcard, text/vcard, etc?).

**Comment by untitaker** [comment]
If this is not a generic WebDAV server but only for CalDAV and CardDAV, what else do you want to upload?

**Comment by jelmer** [comment]
It could currently as well be used for generic WebDAV access, though it is primarily meant to be a CalDAV/CardDAV server. I'd like to keep the boundaries between the calendar/addressbook-specific and the regular WebDAV bits in place as much as possible. 

Would it be sufficient to either create a separate mimetypes.MimeTypes instance to use for lookups and override the entry for .ics there, or just call:

mimetypes.types_map['.ics'] = 'text/calendar'
mimetypes.types_map['.vcf'] = 'text/vcard'

?

**Comment by untitaker** [comment]
That could work, though I'm unsure why you want to do that. It will not be as clear as it is now which content-type `mimetypes` will choose when translating from fileext to content-type.

**Comment by untitaker** [comment]
@jelmer this is ready for review again

**Comment by jelmer** [comment]
Merged, thanks.

**Pull request closed without merging**
